services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: extension_api_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://admin:securepassword123@db:5432/extension_api_db
      - JWT_SECRET=my_secret_key
      - PORT=3000
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npm install &&
             npx sequelize-cli db:migrate --config src/config/config.js --migrations-path src/migrations &&
             npm start"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
