version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: extension_api_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://admin:securepassword123@db:5432/extension_api_db
      - JWT_SECRET=my_secret_key
      - PORT=3000
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15
    container_name: extension_api_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword123
      POSTGRES_DB: extension_api_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
